/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/iTEnBUKfyxD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"

export function FeedContentsComponent() {
  return (
    (<div className="max-w-2xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
      <div className="flex items-center mb-4">
        <Link
          href="#"
          className="inline-flex items-center space-x-2 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
          prefetch={false}>
          <ArrowLeftIcon className="h-5 w-5" />
          <span>식단등록</span>
        </Link>
      </div>
      <div className="flex flex-col items-center space-y-6">
        <img
          src="/placeholder.svg"
          alt="Food Image"
          width={400}
          height={400}
          className="rounded-lg w-full max-h-[400px] object-cover"
          style={{ aspectRatio: "400/400", objectFit: "cover" }} />
        <div className="text-center">
          <h2 className="text-2xl font-bold">Delicious Meal</h2>
        </div>
        <div className="w-full">
          <div className="space-y-4">
            <h2 className="text-xl font-bold">영양정보</h2>
            <hr />
            <div>
              <p className="text-gray-500 dark:text-gray-400">단백질</p>
              <p>20g</p>
            </div>
            <div>
              <p className="text-gray-500 dark:text-gray-400">탄수화물</p>
              <p>30g</p>
            </div>
            <div>
              <p className="text-gray-500 dark:text-gray-400">지방</p>
              <p>20g</p>
            </div>
          </div>
        </div>
        <div className="w-full">
          <Label htmlFor="description" className="block mb-2">
            내용 (선택)
          </Label>
          <Textarea id="description" rows={3} placeholder="" className="w-full" />
        </div>
      </div>
    </div>)
  );
}

function ArrowLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>)
  );
}
