/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MZysAvV8KTG
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export default function MealAddComponent() {
  return (
    <div className="bg-gray-100 dark:bg-gray-800 py-8 px-4 md:px-6 lg:px-8">
      <div className="max-w-md mx-auto grid gap-6">
        <div className="grid gap-6">
          <div className="grid gap-2">
            <h2 className="text-2xl font-bold">식단 등록</h2>
            <p className="text-gray-500 dark:text-gray-400">
              음식 분석 AI가 식단을 분석해드립니다.
            </p>
          </div>
          <form className="bg-white dark:bg-gray-900 rounded-lg p-6 shadow-sm grid gap-4">
            <div className="grid gap-4">
              <div className="grid gap-2">
                <Label htmlFor="meal-name">식단 이름</Label>
                <Input id="meal-name" placeholder="식단 이름을 입력해주세요" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="meal-photo">식단 사진</Label>
                <div className="flex h-40 items-center justify-center rounded-lg border-2 border-dashed border-gray-300 dark:border-gray-600">
                  <div>
                    <div className="text-center text-gray-500 dark:text-gray-400">
                      <UploadIcon className="h-8 w-8 mb-2" />
                      <p>사진을 등록해주세요</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <Button type="submit" className="justify-self-end">
              식단 등록
            </Button>
          </form>
        </div>
        <div className="grid gap-2">
          <h2 className="text-2xl font-bold">영양분 정보</h2>
          <p className="text-gray-500 dark:text-gray-400">
            Here`s a breakdown of the key nutrients in your diet.
          </p>
        </div>
        <div className="grid gap-6">
          <div className="bg-white dark:bg-gray-900 rounded-lg p-6 shadow-sm">
            <h3 className="text-lg font-semibold">단백질</h3>
            <p className="text-gray-500 dark:text-gray-400 mt-2">
              Helps build and repair tissues.
            </p>
            <div className="text-gray-500 dark:text-gray-400">20g</div>
          </div>
          <div className="bg-white dark:bg-gray-900 rounded-lg p-6 shadow-sm">
            <h3 className="text-lg font-semibold">탄수화물</h3>
            <p className="text-gray-500 dark:text-gray-400 mt-2">
              Provides energy for your body.
            </p>
            <div className="text-gray-500 dark:text-gray-400">30g</div>
          </div>
          <div className="bg-white dark:bg-gray-900 rounded-lg p-6 shadow-sm">
            <h3 className="text-lg font-semibold">지방</h3>
            <p className="text-gray-500 dark:text-gray-400 mt-2">
              Supports cell growth and hormone production.
            </p>
            <div className="text-gray-500 dark:text-gray-400">15g</div>
          </div>
        </div>
      </div>
    </div>
  );
}

function UploadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  );
}

function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
