/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1CJo3zV4Ou8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Progress } from "@/components/ui/progress"
import { CardTitle, Card, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function RegisterStep4() {
  const [goal, setGoal] = useState("");
  const [showempty, setShowempty] = useState(false);

  const handleSubmit = (e) => {
    e.preventDefault();

    if(!goal){
      setShowempty(true);
      return;
    }
  };

  return (
    (<div className="flex flex-col h-screen">
      <div className="flex flex-col items-center justify-center px-4 py-8">
        <Progress value={90} className="w-full mb-8" />
        <CardTitle className="mb-8">목표가 무엇인가요?</CardTitle>
        <Card className="w-full">
          <CardContent className="grid gap-6">
            <div className="grid gap-6">
              <Button variant="outline" className={`w-1/2 ${goal === "man" ? 'bg-black text-white' : 'bg-white' }`} onClick={(e) => {
                     setGoal("weightdecrease");
                  }}>
                체중 감소
              </Button>
              <Button variant="outline" className={`w-1/2 ${goal === "man" ? 'bg-black text-white' : 'bg-white' }`} onClick={(e) => {
                     setGoal("weightkeep");
                  }}>
                체중 유지
              </Button>
              <Button variant="outline" className={`w-1/2 ${goal === "man" ? 'bg-black text-white' : 'bg-white' }`} onClick={(e) => {
                     setGoal("weightincrease");
                  }}>
                체중 증가
              </Button>
              <Button variant="outline"className={`w-1/2 ${goal === "man" ? 'bg-black text-white' : 'bg-white' }`} onClick={(e) => {
                     setGoal("healthkeep");
                  }}>
                건강 유지
              </Button>
              <Button variant="outline" className={`w-1/2 ${goal === "man" ? 'bg-black text-white' : 'bg-white' }`} onClick={(e) => {
                     setGoal("others");
                  }}>
                그 외 기타
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
      <div className="mt-auto border-0">
        <Card className="w-full border-0">
          <CardFooter className="flex justify-between gap-4">
            <Button variant="outline" className="w-1/2">
              이전
            </Button>
            <Button type="submit" className="w-1/2" onClick={handleSubmit}>
              완료
            </Button>
          </CardFooter>
        </Card>
      </div>
      {showEmpty && <p className="text-red-500 text-center">모든 항목을 입력해주세요.</p>}
    </div>)
  );
}
