/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/PrqtjfIFBZc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Progress } from "@/components/ui/progress"
import { CardTitle, Card, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function RegisterStep3() {
  const [height, setHeight] = useState("");
  const [weight, setWeight] = useState("");
  const [showempty, setShowempty] = useState(false);

  const handleSubmit = (e) => {
    e.preventDefault();

    if(!height || !weight){
      setShowempty(true);
      return;
    }
  };
  return (
    (<div className="flex flex-col h-screen">
      <div className="flex flex-col items-center justify-center px-4 py-8">
        <Progress value={60} className="w-full mb-8" />
        <CardTitle className="mb-8">키와 몸무게를 알려주세요</CardTitle>
        <Card className="w-full">
          <CardContent className="grid gap-4">
            <div className="grid gap-4">
              <div className="space-y-2">
                <Label htmlFor="height">키</Label>
                <div className="flex items-center gap-2">
                  <Input 
                  id="height" 
                  type="number" 
                  value={height}
                  min="0" max="400" 
                  placeholder="키를 입력해주세요."
                  onChange={(e) => setHeight(e.target.value)}
                  required />
                  <span className="text-gray-500">cm</span>
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="weight">몸무게</Label>
                <div className="flex items-center gap-2">
                  <Input 
                  id="weight" 
                  type="number"
                   min="0" max="300" 
                   placeholder="몸무게를 입력해주세요."
                   onChange={(e) => setWeight(e.target.value)}
                   required />
                  <span className="text-gray-500">kg</span>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
      <div className="mt-auto border-0">
        <Card className="w-full border-0">
          <CardFooter className="flex justify-between gap-2">
            <Button variant="outline" className="w-1/2">
              이전
            </Button>
            <Button type="submit" className="w-1/2" onClick={handleSubmit}>
              다음
            </Button>
          </CardFooter>
        </Card>
      </div>
      {showempty && <p className="text-red-500 text-center">모든 항목을 입력해주세요.</p>}
    </div>)
  );
}
