/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kJaUO3kCxN6
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function RegisterPhase1() {
  return (
    (<div className="flex justify-center items-center h-screen px-4">
      <div className="w-full max-w-md space-y-6">
        <div className="text-center" />
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="userid">아이디</Label>
            <div className="flex gap-2">
              <Input id="userid" type="text" placeholder="사용하실 아이디를 입력해주세요." />
              <Button variant="outline">중복체크</Button>
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">비밀번호</Label>
            <Input id="password" type="password" placeholder="비밀번호를 입력해주세요" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="confirm-password">비밀번호 확인</Label>
            <Input id="confirm-password" type="password" placeholder="비밀번호를 한번 더 입력해주세요" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="nickname">닉네임</Label>
            <div className="flex gap-2">
              <Input id="nickname" placeholder="닉네임을 입력해주세요." />
              <Button variant="outline">중복검사</Button>
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">이메일</Label>
            <Input id="email" type="email" placeholder="이메일을 입력해주세요." />
          </div>
        </div>
        <Button type="submit" className="w-full">
          다음
        </Button>
      </div>
    </div>)
  );
}
